version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    restart: always  # Adicione essa linha
    networks:
      - backend

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: bookstore_db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
